import = [
  "~/.config/alacritty/themes/dracula.toml",
]

[colors.cursor]
cursor = "CellForeground"
text = "CellBackground"

[env]
TERM = "alacritty"

[font]
size = 12.0

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[window]
option_as_alt = "OnlyLeft"

[window.dimensions]
columns = 200
lines = 60

[window.padding]
x = 0
y = 0
