#-------------------------------------------
# Window
#-------------------------------------------
[[plugins]]
repo = 'simeji/winresizer'
on_event = 'BufRead'
hook_source = '''
  let g:winresizer_start_key = '<C-T>'
  let g:winresizer_vert_resize=5
'''

#-------------------------------------------
# Terminal
#-------------------------------------------
[[plugins]]
repo = 'kassio/neoterm'
on_event = 'BufWinEnter'
hook_source = '''
  let g:neoterm_autoinsert = 1
	let g:neoterm_autoscroll = 1
  let g:neoterm_default_mod = 'botright split'
'''
hook_add = '''
  nnoremap <c-t><c-t> :Ttoggle<CR>
  tnoremap <c-t><c-t> <C-\><C-n>:Ttoggle<CR>
  tnoremap <F10> <C-\><C-n>:Tclose!<CR>
'''

[[plugins]]
repo = 'uji/neoterm-rspec.vim'
on_ft = 'ruby'
depends = ['neoterm']
hook_source = '''
 " Add to `.local.vimrc`. default: 'bin/rspec'
 "let g:neoterm_rspec_cmd = 'bin/rspec'
'''
hook_add = '''
  nnoremap <F6> :TermRSpecLine<CR>
'''

#-------------------------------------------
# Text object
#-------------------------------------------
[[plugins]]
repo = 'bronson/vim-trailing-whitespace'
on_event = 'BufWinEnter'
hook_source = '''
  let g:extra_whitespace_ignored_filetypes = ['markdown', 'git']
'''
hook_add = '''
  autocmd BufWritePre * if index(extra_whitespace_ignored_filetypes, &ft) < 0 | :FixWhitespace
'''

[[plugins]]
repo = 'easymotion/vim-easymotion'
on_event = 'VimEnter'
hook_add = '''
  let g:EasyMotion_do_mapping = 0

  " =======================================
  " General Configuration
  " =======================================
  let g:EasyMotion_keys = ';HKLYUIOPNM,QWERTASDGZXCVBJF'
  " Show target key with upper case to improve readability
  let g:EasyMotion_use_upper = 1
  " Jump to first match with enter & space
  let g:EasyMotion_enter_jump_first = 1
  let g:EasyMotion_space_jump_first = 1
'''
hook_post_source = '''
  " =======================================
  " Find Motions
  " =======================================
  " Jump to anywhere you want by just `4` or `3` key strokes without thinking!
  " `s{char}{char}{target}`
  nmap s <Plug>(easymotion-s2)
  xmap s <Plug>(easymotion-s2)
  omap z <Plug>(easymotion-s2)
  " Turn on case sensitive feature
  let g:EasyMotion_smartcase = 1

  " =======================================
  " Line Motions
  " =======================================
  " `JK` Motions: Extend line motions
  map <Leader>j <Plug>(easymotion-j)
  map <Leader>k <Plug>(easymotion-k)
  " keep cursor column with `JK` motions
  let g:EasyMotion_startofline = 0

  map f <Plug>(easymotion-bd-fl)
  map t <Plug>(easymotion-bd-tl)
  map F <Plug>(easymotion-Fl)
  map T <Plug>(easymotion-Tl)
  " :h easymotion-command-line
  " =======================================
  " Search Motions
  " =======================================
  " Extend search motions with vital-over command line interface
  " Incremental highlight of all the matches
  " Now, you don't need to repetitively press `n` or `N` with EasyMotion feature
  " `<Tab>` & `<S-Tab>` to scroll up/down a page with next match
  " :h easymotion-command-line
  nmap g/ <Plug>(easymotion-sn)
  xmap g/ <Plug>(easymotion-sn)
  omap g/ <Plug>(easymotion-tn)

  " =======================================
  " Repeat Motions
  " =======================================
  map <Leader><Leader> <Plug>(easymotion-repeat)
  map <C-n> <Plug>(easymotion-next)
  map <C-p> <Plug>(easymotion-prev)
'''

#-------------------------------------------
# Git
#-------------------------------------------
[[plugins]]
repo = 'tpope/vim-fugitive'
on_event = 'VimEnter'
hook_add = '''
  nnoremap [fugitive] <Nop>
  nmap <Leader>g [fugitive]

  nnoremap [fugitive]d :<C-u>Git diff<CR>
  nnoremap [fugitive]s :<C-u>Git<CR>
  nnoremap [fugitive]l :<C-u>Git log<CR>
  nnoremap [fugitive]c :<C-u>Git commit<CR>
  nnoremap [fugitive]b :<C-u>Git blame<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'VimEnter'
hook_add = '''
  nnoremap g] :GitGutterNextHunk<CR>
  nnoremap g[ :GitGutterPrevHunk<CR>
  nnoremap <C-s> :GitGutterStageHunk<CR>
  nnoremap <C-q> :GitGutterUndoHunk<CR>
'''

[[plugins]]
repo = 'mattn/gist-vim'
on_cmd = 'Gist'
depends = ['webapi-vim']
hook_add = '''
  let g:gist_post_private = 1
'''

[[plugins]]
repo = 'mattn/webapi-vim'

#-------------------------------------------
# Filer
#-------------------------------------------
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = ['NERDTreeFind', 'NERDTreeToggle']
hook_add = '''
  let g:NERDTreeShowHidden = 1
  let g:NERDTreeChDirMode=2
  let g:NERDTreeIgnore=['\.rbc$', '\~$', '\.pyc$', '\.db$', '\.sqlite$', '__pycache__', '\.git$']
  let g:NERDTreeSortOrder=['^__\.py$', '\/$', '*', '\.swp$', '\.bak$', '\~$']
  let g:NERDTreeShowBookmarks=1
  let g:NERDTreeMapOpenInTabSilent = '<RightMouse>'
  let g:NERDTreeWinSize = 50
  let g:NERDTreeQuitOnOpen = 1

  set wildignore+=*/tmp/*,*.so,*.swp,*.zip,*.pyc,*.db,*.sqlite

  nnoremap <silent> <F2> :NERDTreeFind<CR>
  nnoremap <silent> <F3> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'ryanoasis/vim-devicons'
on_source = 'nerdtree'
hook_source = '''
  " loading the plugin
  let g:webdevicons_enable = 1
  " adding the flags to NERDTree
  let g:webdevicons_enable_nerdtree = 1
  " adding to vim-airline's tabline
  let g:webdevicons_enable_airline_tabline = 1
  " adding to vim-airline's statusline
  let g:webdevicons_enable_airline_statusline = 1
  " turn on/off file node glyph decorations (not particularly useful)
  let g:WebDevIconsUnicodeDecorateFileNodes = 1
  " use double-width(1) or single-width(0) glyphs
  " only manipulates padding, has no effect on terminal or set(guifont) font
  let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
'''


[[plugins]]
repo = 'junegunn/fzf'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = 'VimEnter'
depends = ['fzf']
hook_source = '''
  let g:fzf_action = {
        \ 'ctrl-s': 'split',
        \ 'ctrl-v': 'vsplit' }

  set wildmode=list:longest,list:full
  set wildignore+=*.o,*.obj,.git,*.rbc,*.pyc,__pycache__
  let $FZF_DEFAULT_COMMAND =  "find * -path '*/\.*' -prune -o -path 'node_modules/**' -prune -o -path 'target/**' -prune -o -path 'dist/**' -prune -o  -type f -print -o -type l -print 2> /dev/null"

  " The Silver Searcher
  if executable('ag')
    let $FZF_DEFAULT_COMMAND = 'ag --path-to-ignore ~/.agignore --hidden -g ""'
    set grepprg=ag\ --nogroup\ --nocolor

    nnoremap <Space>a :Ag<Space>
    nnoremap <Space>aw :Ag<Space><C-r><C-w>
  endif

  " ripgrep
  if executable('rg')
    let $FZF_DEFAULT_COMMAND = 'rg --files --hidden --follow --glob "!{node_modules/*,.git/*}"'
    set grepprg=rg\ --vimgrep
    command! -bang -nargs=* Find call fzf#vim#grep('rg --column --line-number --no-heading --fixed-strings --ignore-case --hidden --follow --glob "!.git/*" --color "always" '.shellescape(<q-args>).'| tr -d "\017"', 1, <bang>0)

    nnoremap <Space>a :Rg<Space>
    nnoremap <Space>aw :Rg<Space><C-r><C-w>
  endif

  cnoremap <C-P> <C-R>=expand("%:p:h") . "/" <CR>
  nnoremap <Space>f :Files<CR>
  nnoremap <Space>s :GFiles<CR>
  nnoremap <Space>S :GFiles?<CR>
  nnoremap <Space>b :Buffers<CR>
  nnoremap <space>x :Commands<CR>
  " nnoremap <Space>l :BLines<Space>

  " Mapping selecting mappings
  nmap <leader><tab> <plug>(fzf-maps-n)
  xmap <leader><tab> <plug>(fzf-maps-x)
  omap <leader><tab> <plug>(fzf-maps-o)
'''

[[plugins]]
repo = 'justinhoward/fzf-neoyank'
on_source = 'fzf'
hook_source = '''
 nnoremap <leader>y :FZFNeoyank<cr>
 nnoremap <leader>Y :FZFNeoyank " P<cr>
 vnoremap <leader>y :FZFNeoyankSelection<cr>
'''

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = 'context_filetype.vim'
on_ft = ['vim', 'toml']
hook_add = '''
 let g:precious_enable_switch_CursorMoved = { '*': 0, 'help': 1 }
 let g:precious_enable_switchers = {
    \ "*" : {
    \   "setfiletype" : 0
    \ },
    \ "toml" : {
    \   "setfiletype" : 1
    \ },
    \ "html" : {
    \   "setfiletype" : 1
    \ },
    \ "haml" : {
    \   "setfiletype" : 0
    \ },
    \}
 autocmd MyAutoCmd InsertEnter * :PreciousSwitch
 autocmd MyAutoCmd InsertLeave * :PreciousReset"}
'''

#-------------------------------------------
# Register
#-------------------------------------------
[[plugins]]
repo = 'Shougo/neoyank.vim'
on_event = 'VimEnter'

[[plugins]]
repo = 'junegunn/vim-peekaboo'
on_event = 'VimEnter'
hook_source = '''
  let g:peekaboo_window = 'vert bo 80new'
'''

[[plugins]]
repo = 'Shougo/neosnippet'
hook_source = '''
  let g:neosnippet#snippets_directory='~/.cache/dein/repos/github.com/honza/vim-snippets/snippets/'

  imap <C-k> <Plug>(neosnippet_expand_or_jump)
  smap <C-k> <Plug>(neosnippet_expand_or_jump)
  xmap <C-k> <Plug>(neosnippet_expand_target)
  if has('conceal')
    set conceallevel=2 concealcursor=niv
  endif
'''
on_source = ['coc.nvim']
depends = ['neosnippet-snippets']

 [[plugins]]
 repo = 'Shougo/neosnippet-snippets'
#
[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
rev = 'release'
on_event = 'VimEnter'
hook_source = '''
  let g:coc_global_extensions = [
        \ 'coc-solargraph',
        \ 'coc-css',
        \ 'coc-html',
        \ 'coc-json',
        \ 'coc-yaml',
        \ 'coc-dictionary',
        \ 'coc-word',
        \ 'coc-neosnippet',
        \ 'coc-fzf-preview',
        \ 'coc-fish',
        \ ]
'''
hook_add = '''
  inoremap <silent><expr> <TAB>
        \ pumvisible() ? "\<C-n>" :
        \ <SID>check_back_space() ? "\<TAB>" :
        \ coc#refresh()
  inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"

  function! s:check_back_space() abort
    let col = col('.') - 1
    return !col || getline('.')[col - 1]  =~# '\s'
  endfunction

  nmap <silent> gd <Plug>(coc-definition)
  nmap <silent> gy <Plug>(coc-type-definition)
  nmap <silent> gi <Plug>(coc-implementation)
  nmap <silent> gr <Plug>(coc-references)

  " Use K to show documentation in preview window.
  nnoremap <silent> K :call <SID>show_documentation()<CR>

  function! s:show_documentation()
    if (index(['vim','help'], &filetype) >= 0)
      execute 'h '.expand('<cword>')
    elseif (coc#rpc#ready())
      call CocActionAsync('doHover')
    else
      execute '!' . &keywordprg . " " . expand('<cword>')
    endif
  endfunction
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'jgdavey/vim-blockle'
on_ft = 'ruby'
hook_source = '''
  let g:blockle_mapping = '<Leader>rb'
'''

[[plugins]]
repo = 'ecomba/vim-ruby-refactoring'
on_ft = 'ruby'

[[plugins]]
repo = 'tpope/vim-haml'
on_ft = 'haml'

[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = 'slim'

[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby', 'eruby', 'slim', 'haml']

[[plugins]]
repo = 'jvanja/vim-bootstrap4-snippets'
on_ft = ['erb', 'slim', 'haml']

[[plugins]]
repo = 'alvan/vim-closetag'
on_ft = ['erb', 'html']

[[plugin]]
repo = 'gabrielelana/vim-markdown'
on_ft = 'markdown'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = 'markdown'
hook_source = '''
  let g:previm_open_cmd = 'open'

  nnoremap [previm] <Nop>
  nmap <Leader>p [previm]
  nnoremap <silent> [previm]o :<C-u>PrevimOpen<CR>
  nnoremap <silent> [previm]r :call previm#refresh()<CR>
'''

#-------------------------------------------
# HTML
#-------------------------------------------
[[plugins]]
repo = 'kchmck/vim-coffee-script'
on_ft = ['coffee']

#-------------------------------------------
# HTML
#-------------------------------------------
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html', 'eruby', 'haml']

#-------------------------------------------
# CSS
#-------------------------------------------
[[plugins]]
repo = 'ap/vim-css-color'
on_ft = ['css', 'scss']

#-------------------------------------------
# Fish
#-------------------------------------------
[[plugins]]
repo = 'dag/vim-fish'
on_ft = 'fish'
